In [19]:
import pandas as pd
import numpy as np
import copy
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('gender.csv')
df.head()

  Favorite Color    Favorite Music Favorite Beverage Favorite Softdrink Gender
0           Cool              Rock             Vodka         7UP/Sprite      F
1        Neutral           Hip hop             Vodka    Coca Cola/Pepsi      F
2           Warm              Rock              Wine    Coca Cola/Pepsi      F
3           Warm  Folk/Traditional           Whiskey              Fanta      F
4           Cool              Rock             Vodka    Coca Cola/Pepsi      F

In [3]:
df.shape

(66, 5)

In [4]:
df.isnull().sum()

Favorite Color        0
Favorite Music        0
Favorite Beverage     0
Favorite Softdrink    0
Gender                0
dtype: int64

In [5]:
print(pd.unique(df['Favorite Color']))
print(pd.unique(df['Favorite Music']))

['Cool' 'Neutral' 'Warm']
['Rock' 'Hip hop' 'Folk/Traditional' 'Jazz/Blues' 'Pop' 'Electronic'
 'R&B and soul']

In [6]:
for col in df.columns:
    print(col)
    print(pd.unique(df[col]))

Favorite Color
['Cool' 'Neutral' 'Warm']
Favorite Music
['Rock' 'Hip hop' 'Folk/Traditional' 'Jazz/Blues' 'Pop' 'Electronic'
 'R&B and soul']
Favorite Beverage
['Vodka' 'Wine' 'Whiskey' "Doesn't drink" 'Other' 'Beer']
Favorite Softdrink
['7UP/Sprite' 'Coca Cola/Pepsi' 'Fanta' 'Other']
Gender
['F' 'M']

In [16]:
import category_encoders as ce

In [17]:
df1 = df.copy()
binary_encoder = ce.BinaryEncoder(cols=['Gender'])
binary_encoder.fit_transform(df1)

C:\Users\sumon\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

,Favorite Color,Favorite Music,Favorite Beverage,Favorite Softdrink,Gender_0,Gender_1
0,Cool,Rock,Vodka,7UP/Sprite,0,1
1,Neutral,Hip hop,Vodka,Coca Cola/Pepsi,0,1
2,Warm,Rock,Wine,Coca Cola/Pepsi,0,1
3,Warm,Folk/Traditional,Whiskey,Fanta,0,1
4,Cool,Rock,Vodka,Coca Cola/Pepsi,0,1
...,...,...,...,...,...,...
61,Cool,Rock,Vodka,Coca Cola/Pepsi,1,0
62,Cool,Hip hop,Beer,Coca Cola/Pepsi,1,0
63,Neutral,Hip hop,Doesn't drink,Fanta,1,0
64,Cool,Rock,Wine,Coca Cola/Pepsi,1,0
65,Cool,Electronic,Beer,Coca Cola/Pepsi,1,0

# Replace

In [18]:
['Cool' 'Neutral' 'Warm']
df2 = df.copy()
replace_map = {'Favorite Color' : {'Cool' : 1, 'Neutral' : 2,'Warm' : 3 }}
df2.replace(replace_map)

,Favorite Color,Favorite Music,Favorite Beverage,Favorite Softdrink,Gender
0,1,Rock,Vodka,7UP/Sprite,F
1,2,Hip hop,Vodka,Coca Cola/Pepsi,F
2,3,Rock,Wine,Coca Cola/Pepsi,F
3,3,Folk/Traditional,Whiskey,Fanta,F
4,1,Rock,Vodka,Coca Cola/Pepsi,F
...,...,...,...,...,...
61,1,Rock,Vodka,Coca Cola/Pepsi,M
62,1,Hip hop,Beer,Coca Cola/Pepsi,M
63,2,Hip hop,Doesn't drink,Fanta,M
64,1,Rock,Wine,Coca Cola/Pepsi,M
65,1,Electronic,Beer,Coca Cola/Pepsi,M

# Label Encoding

In [21]:
df_lbl = df.copy()
lbl_encoder = LabelEncoder()
df_lbl['Favorite Music'] = lbl_encoder.fit_transform(df_lbl['Favorite Music'])

df_lbl

   Favorite Color  Favorite Music Favorite Beverage Favorite Softdrink Gender
0            Cool               6             Vodka         7UP/Sprite      F
1         Neutral               2             Vodka    Coca Cola/Pepsi      F
2            Warm               6              Wine    Coca Cola/Pepsi      F
3            Warm               1           Whiskey              Fanta      F
4            Cool               6             Vodka    Coca Cola/Pepsi      F
..            ...             ...               ...                ...    ...
61           Cool               6             Vodka    Coca Cola/Pepsi      M
62           Cool               2              Beer    Coca Cola/Pepsi      M
63        Neutral               2     Doesn't drink              Fanta      M
64           Cool               6              Wine    Coca Cola/Pepsi      M
65           Cool               0              Beer    Coca Cola/Pepsi      M

[66 rows x 5 columns]

# One-Hot encoding

In [27]:
df_one_hot = df.copy()


df_one_hot = pd.get_dummies(df_one_hot,columns=['Gender'] ,prefix = ['Gender'],drop_first=True)

df_one_hot

,Favorite Color,Favorite Music,Favorite Beverage,Favorite Softdrink,Gender_M
0,Cool,Rock,Vodka,7UP/Sprite,0
1,Neutral,Hip hop,Vodka,Coca Cola/Pepsi,0
2,Warm,Rock,Wine,Coca Cola/Pepsi,0
3,Warm,Folk/Traditional,Whiskey,Fanta,0
4,Cool,Rock,Vodka,Coca Cola/Pepsi,0
...,...,...,...,...,...
61,Cool,Rock,Vodka,Coca Cola/Pepsi,1
62,Cool,Hip hop,Beer,Coca Cola/Pepsi,1
63,Neutral,Hip hop,Doesn't drink,Fanta,1
64,Cool,Rock,Wine,Coca Cola/Pepsi,1
65,Cool,Electronic,Beer,Coca Cola/Pepsi,1

# Frequency Encoding

In [42]:
data_freq = pd.read_csv('gender.csv')
fe = data_freq.groupby("Favorite Beverage").size()

fe_ = fe/len(data_freq)
data_freq["fe_Favorite_Beverage"] = data_freq["Favorite Beverage"].map(fe_).round(2)
data_freq.drop(['Favorite Beverage'],axis=1)

,Favorite Color,Favorite Music,Favorite Softdrink,Gender,fe_Favorite_Beverage
0,Cool,Rock,7UP/Sprite,F,0.14
1,Neutral,Hip hop,Coca Cola/Pepsi,F,0.14
2,Warm,Rock,Coca Cola/Pepsi,F,0.15
3,Warm,Folk/Traditional,Fanta,F,0.14
4,Cool,Rock,Coca Cola/Pepsi,F,0.14
...,...,...,...,...,...
61,Cool,Rock,Coca Cola/Pepsi,M,0.14
62,Cool,Hip hop,Coca Cola/Pepsi,M,0.20
63,Neutral,Hip hop,Fanta,M,0.21
64,Cool,Rock,Coca Cola/Pepsi,M,0.15
65,Cool,Electronic,Coca Cola/Pepsi,M,0.20